name: misete-accounts

type: rails

up:
  - homebrew:
    - mysql-client@5.7:
        or:        [mysql@5.7]
        conflicts: [mysql-connector-c, mysql, mysql-client]
    # - another_package
  - ruby: 2.6.3
  - node:
      version: v10.11.0
      yarn: 1.12.3
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: misete-accounts.railgun
      user: root
      password: ''
      database: misete_accounts_development

server:
  port: 41309

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://misete-accounts.myshopify.io
  #ops:
    # - https://datadog.link
    # - https://bugsnag.link
    # - https://kafka.link
