default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: misete
  password: isthizatheway
  pool: 5

development:
  <<: *default
  database: misete_accounts_development

test:
  <<: *default
  database: misete_accounts_test

production:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  username: <%= ENV['DATABASE_PASSWORD'] %>
  database: misete_accounts
